word = input("Please enter an old password: ")
word = word.replace('s', '$')
word = word.replace('a', '@')
word = word.replace('o', '0')
word = word.replace('i', '!')
word = word.replace('e', '3')
word = word.replace('b', '8')
word = word.replace('g', '9')
word = word.replace('t', '+')
word = word.replace('l', '|')
word = word.replace('z', '2')
word = word.replace('c', '(')
word = word.replace('d', '|)')
word = word.replace('f', '|=')
word = word.replace('h', '|-|')
word = word.replace('j', '_/')
word = word.replace('k', '|<')
word = word.replace('m', '|\/|')
word = word.replace('n', '|\|')
word = word.replace('p', '|>')
word = word.replace('q', '0,')
word = word.replace('r', '|2')
word = word.replace('u', '|_|')
word = word.replace('v', '\/')
word = word.replace('w', '\/\/')
word = word.replace('x', '><')
word = word.replace('y', '`/')
word = word.replace('1', '!')
word = word.replace('2', '@')
word = word.replace('3', '#')
word = word.replace('4', '$')
word = word.replace('5', '%')
word = word.replace('6', '^')
word = word.replace('7', '&')
word = word.replace('8', '*')
word = word.replace('9', '(')
word = word.replace('0', ')')

password = word

print(f"Your new password is: {password}")
